#!/bin/bash

# To backup everything:
for i in /srv/; do sudo zip -r "/home/$USER/${i%/}.zip" "$i"; done

# To restore everything:
sudo unzip -d / srv.zip

TO BACKUP:

docker save urbancompasspony/razera > razera.tar

TO RESTORE:

docker load < razera.tar

Then run the container with common parameters
