#!/bin/bash

# IP FIXO DO NOVO CONTAINER
LOCALIP="$1"
# SENHA PARA O PIHOLE
MYPASSWORD="$2"
# USUARIO DO HOST
USERNAME="$3"

mkdir -p /home/"$USERNAME"/.CONTAINERS/

docker run \
--name=pihole \
--network macvlan \
--ip=$LOCALIP \
--dns=1.1.1.1  \
--dns=127.0.0.1 \
--hostname=pi.hole \
-e SERVERIP=$LOCALIP \
-e WEBPASSWORD=$MYPASSWORD \
-v /etc/localtime:/etc/localtime:ro \
-v /home/"$USERNAME"/.CONTAINERS/pihole/pihole/:/etc/pihole \
-v /home/"$USERNAME"/.CONTAINERS/pihole/dnsmasq.d/:/etc/dnsmasq.d \
-p 80:80 \
-p 443:443 \
-p 67:67/tcp \
-p 67:67/udp \
-p 53:53/tcp \
-p 53:53/udp \
--restart=unless-stopped \
pihole/pihole:latest
