#!/bin/bash

# Some information for multisites (replication with more DC)
# After everything up and ok, run this:
# docker exec sambaaddc samba-tool drs showrepl
# And catch the DSA object GUID.
# Remove your docker container, keep the files and run again adding this line:
# --add-host 14300161-0666-4cb6-8f46-4cb41f2ceda6._msdcs.$FQDN:$LOCALIP \
# Where is --add-host

# Change here to create a new domain controller!
FQDN="ad.atomic.local"
LOCALIP="172.20.0.42"
MYPASSWORD="P4ssw0rd"
GATEWAYS="172.20.0.1"
HOSTNAME="atomicpi"
NAME="sambaaddc"
NETWORKLAN="macvlan"

docker run -t -i \
        --name $NAME \
        --dns-search $FQDN \
        --dns $LOCALIP \
        --dns $GATEWAYS \
        --add-host $HOSTNAME.$FQDN:$LOCALIP \ # --add-host 14300161-0666-4cb6-8f46-4cb41f2ceda6._msdcs.$FQDN:$LOCALIP \
        --privileged \
        --network $NETWORKLAN \
        --ip=$LOCALIP \
        --restart=unless-stopped \
        -h $HOSTNAME \
        -e DOMAIN=$FQDN \
        -e DOMAINPASS=$MYPASSWORD \
        -e DNSFORWARDER=$GATEWAYS \
        -e HOSTIP=$LOCALIP \
        -p $LOCALIP:53:53 \
        -p $LOCALIP:53:53/udp \
        -p $LOCALIP:88:88 \
        -p $LOCALIP:88:88/udp \
        -p $LOCALIP:135:135 \
        -p $LOCALIP:137:137 \
        -p $LOCALIP:137:137/udp \
        -p $LOCALIP:138:138 \
        -p $LOCALIP:138:138/udp \
        -p $LOCALIP:139:139 \
        -p $LOCALIP:389:389 \
        -p $LOCALIP:389:389/udp \
        -p $LOCALIP:445:445 \
        -p $LOCALIP:464:464 \
        -p $LOCALIP:464:464/udp \
        -p $LOCALIP:636:636 \
        -p $LOCALIP:1024-1044:1024-1044 \
        -p $LOCALIP:3268-3269:3268-3269 \
        -v /etc/localtime:/etc/localtime:ro \
        -v $(pwd)/samba/data/:/var/lib/samba \
        -v $(pwd)/samba/config/samba:/etc/samba/external \
        nowsci/samba-domain
