#!/bin/bash

# NOME DA NOVA FLORESTA
FQDN="ad.atomic.local"
# IP FIXO DO NOVO CONTAINER
LOCALIP="172.20.0.42"
# SENHA DO USUARIO ADMINISTRATOR
MYPASSWORD="P4ssw0rd"
# DEFINA O DNS QUE O DOMINIO USARÁ
DNSFW="172.20.0.41"
# HOSTNAME DO CONTAINER
HOSTNAME="atomicpi"
# NOME DO CONTAINER
NAME="dominio"
# USUARIO DO HOST
USERNAME="urbancompasspony"
# PLACA DE REDE A SER USADA
NETWORKLAN="macvlan"

mkdir -p /home/"$USERNAME"/.CONTAINERS/

docker run -t -i \
        --name $NAME \
        --dns-search $FQDN \
        --dns $LOCALIP \
        --dns $DNSFW \
        --add-host "$HOSTNAME"."$FQDN":"$LOCALIP" \
        --privileged \
        --network $NETWORKLAN \
        --ip=$LOCALIP \
        --restart=unless-stopped \
        -h $HOSTNAME \
        -e "DOMAIN=$FQDN" \
        -e "DOMAINPASS=$MYPASSWORD" \
        -e "DNSFORWARDER=$DNSFW" \
        -e "HOSTIP=$LOCALIP" \
        -p $LOCALIP:53:53 \
        -p $LOCALIP:53:53/udp \
        -p $LOCALIP:88:88 \
        -p $LOCALIP:88:88/udp \
        -p $LOCALIP:135:135 \
        -p $LOCALIP:137:137 \
        -p $LOCALIP:137:137/udp \
        -p $LOCALIP:138:138 \
        -p $LOCALIP:138:138/udp \
        -p $LOCALIP:139:139 \
        -p $LOCALIP:389:389 \
        -p $LOCALIP:389:389/udp \
        -p $LOCALIP:445:445 \
        -p $LOCALIP:464:464 \
        -p $LOCALIP:464:464/udp \
        -p $LOCALIP:636:636 \
        -p $LOCALIP:1024-1044:1024-1044 \
        -p $LOCALIP:3268-3269:3268-3269 \
        -v /etc/localtime:/etc/localtime:ro \
        -v /home/"$USERNAME"/.CONTAINERS/active_directory/data/:/var/lib/samba \
        -v /home/"$USERNAME"/.CONTAINERS/active_directory/config/:/etc/samba/external \
        -v /mnt:/mnt \
        urbancompasspony/domain

# If some DC join to this DC, use this if there is any error:
#REMOTEDC="172.20.0.44"
#REMOTEHOSTNAME="btomicpi"

#--add-host 14300161-0666-4cb6-8f46-4cb41f2ceda6._msdcs.$REMOTEHOSTNAME.$FQDN:$REMOTEDC \
