#!/bin/bash

# IP for web access. Default port is 8443!
# DOES NOT WORK on ARM arch.
SETIP="192.168.0.15"

docker run -d \
  --name=unifi \
  --network macvlan \
  --ip=$SETIP \
  --dns=1.1.1.1  \
  --dns=127.0.0.1 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e MEM_LIMIT=1024 `#optional` \
  -e MEM_STARTUP=1024 `#optional` \
  -p 8443:8443 \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 1900:1900/udp `#optional` \
  -p 8843:8843 `#optional` \
  -p 8880:8880 `#optional` \
  -p 6789:6789 `#optional` \
  -p 5514:5514/udp `#optional` \
  -v $(pwd)/unifi/:/config \
  -v /etc/localtime:/etc/localtime:ro \
  --restart unless-stopped \
  lscr.io/linuxserver/unifi-controller:latest
