#!/bin/bash

# Passe o parâmetro antes, ou edite a linha abaixo adicionando o parâmetro entre aspas!

# IP FIXO DO NOVO CONTAINER
SETIP="$1"
# USUARIO DO HOST
USERNAME="$2"

[ $(arch) = "x86_64" ] && {
  echo "Sistema compatível!"
  echo "Ao finalizar, acesse pelo IP definido e na Porta 8443"
} || {
  echo "Sistema incompatível com esta arquitetura. Saindo."
  exit
}

mkdir -p /home/"$USERNAME"/.CONTAINERS/

docker run -d \
  --name=unifi \
  --network macvlan \
  --ip=$SETIP \
  --dns=1.1.1.1  \
  --dns=127.0.0.1 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e MEM_LIMIT=1024 `#optional` \
  -e MEM_STARTUP=1024 `#optional` \
  -p 8443:8443 \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 1900:1900/udp `#optional` \
  -p 8843:8843 `#optional` \
  -p 8880:8880 `#optional` \
  -p 6789:6789 `#optional` \
  -p 5514:5514/udp `#optional` \
  -v /etc/localtime:/etc/localtime:ro \
  -v /home/"$USERNAME"/.CONTAINERS/unifi/:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/unifi-controller:latest
