#!/bin/bash

NOMECONTAINER="mysql-generic"

docker_repo="mysql"
imagem="mysql"

CustmN2="local_ip"
CustmN3="mysql_pw"
CustmN4="database"
CustmN5="db_user"
CustmN6="db_pass"
CustmN7="db_path"
CustmN8="version"
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3=""
VALUE4=""
VALUE5=""
VALUE6=""
VALUE7="/srv/containers/$NOMECONTAINER"
VALUE8="conferir-8.0.42"
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"
  sudo mkdir -p $VALUE7
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e MYSQL_ROOT_PASSWORD="$VALUE3" \
    -e MYSQL_DATABASE="$VALUE4" \
    -e MYSQL_USER="$VALUE5" \
    -e MYSQL_PASSWORD="$VALUE6" \
    -v $VALUE7/mysql:/var/lib/mysql \
    "$docker_repo":"$VALUE8"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e MYSQL_ROOT_PASSWORD="$VALUE3" \
  -e MYSQL_DATABASE="$VALUE4" \
  -e MYSQL_USER="$VALUE5" \
  -e MYSQL_PASSWORD="$VALUE6" \
  -v $VALUE7/mysql:/var/lib/mysql \
  "$docker_repo":"$VALUE8"
}

function docker_extras {

:; }

execute_main

exit 0
