#!/bin/bash

# NOME DO BANCO DE DADOS
export var1
# IP FIXO DO NOVO CONTAINER
export var2
# NOVA SENHA DO ROOT MYSQL
export var3
# NOVO BANCO DE DADOS
export var4
# USUARIO BANCO DE DADOS
export var5
# SENHA DO BANCO DE DADOS
export var6
# CAMINHO DO BANCO DE DADOS
export var7

# Global config for replication:
export NOMECONTAINER="mysql-algo"

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function checkB {
  export var1; export var2; export var3; export var4; export var5; export var6; export var7

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    dialog --title "Dados de $NOMECONTAINER encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $NOMECONTAINER" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)
        var2=$(sed -n '2p' /srv/containers/$NOMECONTAINER/Information)
        var3=$(sed -n '3p' /srv/containers/$NOMECONTAINER/Information)
        var4=$(sed -n '4p' /srv/containers/$NOMECONTAINER/Information)
        var5=$(sed -n '5p' /srv/containers/$NOMECONTAINER/Information)
        var6=$(sed -n '6p' /srv/containers/$NOMECONTAINER/Information)
        var7=$(sed -n '7p' /srv/containers/$NOMECONTAINER/Information)

        [ $(docker stop "$NOMECONTAINER") ] && {
          docker rm "$NOMECONTAINER"

          create
        } || {
          create
        }
        
      } || {
        docker stop "$NOMECONTAINER"
        docker rm "$NOMECONTAINER"
        
        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$NOMECONTAINER-$datetime.zip" -r /srv/containers/$NOMECONTAINER
        
        rm -iR /srv/containers/"$NOMECONTAINER"

        menu
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    menu
    }
}

function menu {
  export var1; export var2; export var3; export var4; export var5; export var6; export var7

VALUE1="mysql-algo"; VALUE2=""; VALUE3=""; VALUE4=""; VALUE5=""; VALUE6=""; VALUE7="/srv/containers/mysql-algo"

  VALUE0=$(dialog --ok-label "Criar" --title "Novo Container" --form "Container: $NOMECONTAINER" 14 40 0 \
"NameCont:" 1 1 "$VALUE1" 1 10 20 0 \
"Local IP:" 2 1 "$VALUE2" 2 10 20 0 \
"MySQL PW" 3 1 "$VALUE3" 3 10 20 0 \
"DataBase" 4 1 "$VALUE4" 4 10 20 0 \
"DB User " 5 1 "$VALUE5" 5 10 20 0 \
"DB Pass " 6 1 "$VALUE6" 6 10 20 0 \
"DB PATH :" 7 1 "$VALUE7" 7 10 40 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  var2=$(echo "$VALUE0" | sed -n 2p)
  var3=$(echo "$VALUE0" | sed -n 3p)
  var4=$(echo "$VALUE0" | sed -n 4p)
  var5=$(echo "$VALUE0" | sed -n 5p)
  var6=$(echo "$VALUE0" | sed -n 6p)
  var7=$(echo "$VALUE0" | sed -n 7p)

  [ -z "$var1" ] || [ -z "$var2" ] || [ -z "$var7" ] && {
    dialog --title "ERRO" --msgbox "Não deixe vazios os campos 1, 2 e 7!" 8 40
    menu
  } || {
    checkC
    }
}

function checkC {
  #IPMachine=$(hostname -I | awk '{print $1}')
  MyIP=$(cat /srv/containers/scripts/myip)
  [ "$MyIP" = "$var1" ] && {
    dialog --title "ERRO" --msgbox "Conflito de IP detectado! \nMude para outro IP." 6 40
    menu
  } || {
    create
  }
}

function create {
  export var1; export var2; export var3; export var4; export var5; export var6; export var7

  mkdir -p /srv/containers/"$NOMECONTAINER"
  touch /srv/containers/"$NOMECONTAINER"/Information
  echo "$var1" > /srv/containers/"$NOMECONTAINER"/Information
  echo "$var2" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var3" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var4" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var5" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var6" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var7" >> /srv/containers/"$NOMECONTAINER"/Information

  docker run -d \
  --name $var1 \
  --ip=$var2 \
  --dns=1.1.1.1  \
  --dns=127.0.0.1 \
  --network macvlan \
  --hostname=$var1 \
  --restart=unless-stopped \
  --no-healthcheck \
  -v /etc/localtime:/etc/localtime:ro \
  -v "$var7"/mysql:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD="$var3" \
  -e MYSQL_DATABASE="$var4" \
  -e MYSQL_USER="$var5" \
  -e MYSQL_PASSWORD="$var6" \
  mysql:8
}

# Start
checkA
checkB

docker network connect bridge $var1

echo "Finalizado!"
echo "Aguarde aproximadamente 2 minutos para início do banco de dados."
echo "Localização do banco de dados definida em: $var7"

# Unset vars:
unset var1
unset var2
unset var3
unset var4
unset var5
unset var6
unset var7

exit 1
