#!/bin/bash

NOMECONTAINER="nut-gui"

docker_repo="ghcr.io/superioone/nut_webgui:latest"
imagem="nut"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="username"
CustmN5="password"
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="admin"
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e UPSD_ADDR=$VALUE2 \
    -e UPSD_USER=$VALUE4 \
    -e UPSD_PASS=$VALUE5 \
    -p 9000:9000 \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e UPSD_ADDR=$VALUE2 \
  -e UPSD_USER=$VALUE4 \
  -e UPSD_PASS=$VALUE5 \
  -p 9000:9000 \
  "$docker_repo"

# Examples
# PATH: $VALUE3 \
# -e variavel1="$VALUE4" \
# --privileged
# --network host --add-host=host.docker.internal:host-gateway \
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

execute_main

exit 0
