#!/bin/bash

# IP FIXO DO NOVO CONTAINER
export var1
# NOME DO COMPARTILHAMENTO E DO CONTAINER!
export var2
# CAMINHO DO DIRETÓRIO DE COMPARTILHAMENTO
export var3
# CAMINHOS EXTRAS
export var4
# PLACA DE REDE A SER USADA
NETWORKLAN="macvlan"

[ $(arch) = "x86_64" ] && {
  REPOSITORY="urbancompasspony/migrate-samba"
} || {
  REPOSITORY="urbancompasspony/migrate-samba-arm"
}

function menu {
  export var1; export var2; export var3; export var4

  VALUE1=""; VALUE2="samba"; VALUE3="/mnt"; VALUE4="-v /mnt:/mnt"

  VALUE0=$(dialog --ok-label "Criar" --title "Novo Container" --form "New Samba Share" 11 40 0 \
"Local IP: " 1 1 "$VALUE1" 1 10 20 0 \
"Shr Name:" 2 1 "$VALUE2" 2 10 20 0 \
"MNT Path:" 3 1 "$VALUE3" 3 10 20 0 \
"EXT Path:" 4 1 "$VALUE4" 4 10 20 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  var2=$(echo "$VALUE0" | sed -n 2p)
  var3=$(echo "$VALUE0" | sed -n 3p)
  var4=$(echo "$VALUE0" | sed -n 4p)
  
  [ -z "$var1" ] || [ -z "$var2" ] || [ -z "$var3" ] && {
    dialog --title "ERRO" --msgbox "Não deixe os campos 1, 2 e/ou 3 vazios!" 8 40
    menu
  } || {
    checkB
    }
}

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function checkB {
  export var1; export var2; export var3; export var4

  [ -f "/srv/containers/$var2/Information" ] && {
    dialog --title "Dados de $var2 encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $var2" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$var2/Information)
        var2=$(sed -n '2p' /srv/containers/$var2/Information)
        var3=$(sed -n '3p' /srv/containers/$var2/Information)
        var4=$(sed -n '4p' /srv/containers/$var2/Information)

        [ $(docker stop "$var2") ] && {
          docker rm "$var2"

          create
        } || {
          create
        }
        
      } || {
        docker stop "$var2"
        docker rm "$var2"
        
        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$var2-$datetime.zip" -r /srv/containers/$var2
        
        rm -R /srv/containers/"$var2"

        configfiles
        create
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    configfiles
    create
    }
}

function configfiles {
  wget https://codeload.github.com/urbancompasspony/samba/zip/refs/heads/main -P /srv/containers/
  unzip -d /srv/containers/ /srv/containers/main
  rm /srv/containers/main
  mv /srv/containers/samba-main /srv/containers/"$var2"
}

function create {
  export var1; export var2; export var3; export var4
  
  mkdir -p /srv/containers/"$var2"
  touch /srv/containers/"$var2"/Information
  echo "$var1" > /srv/containers/"$var2"/Information
  echo "$var2" >> /srv/containers/"$var2"/Information
  echo "$var3" >> /srv/containers/"$var2"/Information
  echo "$var4" >> /srv/containers/"$var2"/Information

docker run -d \
-h $var2 \
--ip $var1 \
--name $var2 \
--privileged \
--dns 127.0.0.1 \
--dns 1.1.1.1 \
--restart=unless-stopped \
--no-healthcheck \
-v /etc/localtime:/etc/localtime:ro \
--network $NETWORKLAN \
-v /srv/containers/"$var2"/etc/samba:/etc/samba \
-v /srv/containers/"$var2"/cache/samba:/var/cache/samba \
-v /srv/containers/"$var2"/lib/samba:/var/lib/samba \
-v /srv/containers/"$var2"/log/samba:/var/log/samba \
-v /srv/containers/"$var2"/run/samba:/run/samba \
-v "$var3":/mnt "$var4" \
$REPOSITORY

sudo chmod 777 -R /srv/containers/"$var2"/log/
sudo chmod 0700 -R /srv/containers/"$var2"/log/samba/cores
sudo docker exec $var2 chmod 777 -R /var/log
}

function clean {
  unset var1
  unset var2
  unset var3
  unset var4
}

# Start
checkA
menu
clean

echo " "
echo "Samba Default Share on $var1/shared with user and password ubuntu!"
echo " "

exit
