#!/bin/bash

[ "$EUID" -ne 0 ] && {
  echo "Run this script as Root!"
  exit
  }

migration_name="dominio"

echo "Setting Migration Name: $migration_name"
datetime=$(date +"%d-%m-%H-%M")

echo "Stopping SAMBA-AD-DC"
sudo systemctl stop samba-ad-dc

echo "Creating data, config and log folders inside $migration_name"
sudo mkdir -p /srv/containers/$migration_name/log
sudo mkdir -p /srv/containers/$migration_name/data
sudo mkdir -p /srv/containers/$migration_name/config

echo "Creating syslog and Information files"
sudo touch /srv/containers/$migration_name/log/syslog && chmod 777 /srv/containers/$migration_name/log/syslog
sudo touch /srv/containers/$migration_name/Information

echo "Populating Information file"
echo "CHECK EVERYTHING - REMOVE THIS LINE TO CHECK IF YOU UNDERTOOD!" > /srv/containers/$migration_name/Information
echo "FQDN - ad.example.local" >> /srv/containers/$migration_name/Information
echo "DOMAIN IP" >> /srv/containers/$migration_name/Information
echo "Admin Password" >> /srv/containers/$migration_name/Information
echo "LAN DNS - 192.168.0.11" >> /srv/containers/$migration_name/Information
echo "$HOSTNAME" >> /srv/containers/$migration_name/Information
echo "macvlan" >> /srv/containers/$migration_name/Information
echo "-v /mnt:/mnt" >> /srv/containers/$migration_name/Information

echo "Copying folders"
sudo rsync -vaAxhHt /var/lib/samba/ /srv/containers/$migration_name/data/
sudo rsync -vaAxhHt /etc/samba/ /srv/containers/$migration_name/config/

echo "Starting SAMBA-AD-DC"
sudo systemctl start samba-ad-dc

sudo nano /srv/containers/$migration_name/Information

echo "#################################"
echo "# SYSTEM MIGRATED SUCCESSFULLY! #"
echo "#################################"
echo " "
echo "Press Enter to Exit."
read; sleep 1

# RUN
# echo "Creating BKP-Resolv inside /etc"
# cp /etc/resolv.conf /etc/resolv-"$datetime"
# echo "Stopping SAMBA-AD-DC"
# systemctl stop samba-ad-dc
# echo "Disabling SAMBA-AD-DC"
# systemctl disable samba-ad-dc
# echo "Masking SAMBA-AD-DC"
# systemctl mask samba-ad-dc
# echo "Unmasking SYSTEMD-RESOLVED"
# systemctl unmask systemd-resolved
# echo "Enabling SYSTEMD-RESOLVED"
# systemctl enable systemd-resolved
# touch /etc/resolv.conf
# echo "nameserver 127.0.0.53" > /etc/resolv.conf
# echo "Starting SYSTEMD-RESOLVED"
# systemctl start systemd-resolved

exit 1
