#!/bin/bash

NOMECONTAINER="simple-web-chat"

docker_repo="urbancompasspony/simple-web-chat"
imagem="swc"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4=""
CustmN5=""
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4=""
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/data
  sudo touch /srv/containers/"$NOMECONTAINER"/data/messages.json
  echo '{"messages":[]}' | sudo tee /srv/containers/"$NOMECONTAINER"/data/messages.json
  sudo touch /srv/containers/"$NOMECONTAINER"/data/users.json
  echo '{"users":[]}' | sudo tee /srv/containers/"$NOMECONTAINER"/data/users.json
  sudo touch /srv/containers/"$NOMECONTAINER"/data/container.log
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

  chat-apache-php

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    --no-healthcheck \
    -p 8080:80 \
    -v /srv/containers/"$NOMECONTAINER"/data/messages.json:/var/www/html/data/messages.json \
    -v /srv/containers/"$NOMECONTAINER"/data/users.json:/var/www/html/data/users.json \
    -v /srv/containers/"$NOMECONTAINER"/data/container.log:/srv/containers/simple-web-chat/data/container.log \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  --no-healthcheck \
  -v /srv/containers/"$NOMECONTAINER"/data/messages.json:/var/www/html/data/messages.json \
  -v /srv/containers/"$NOMECONTAINER"/data/users.json:/var/www/html/data/users.json \
  -v /srv/containers/"$NOMECONTAINER"/data/container.log:/srv/containers/simple-web-chat/data/container.log \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

execute_main

exit 0
