#!/bin/bash

# Global config for replication:
export NOMECONTAINER="lancache"

# IP FIX DOS CONTAINERS LANCACHE
export var1
# IP do DNS alvo na rede
export var1
# DIRETÓRIO DO CACHE
export var3

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function checkB {
  export var1; export var2; export var3

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    dialog --title "Dados de $NOMECONTAINER encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $NOMECONTAINER" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)
        var2=$(sed -n '2p' /srv/containers/$NOMECONTAINER/Information)
        var3=$(sed -n '3p' /srv/containers/$NOMECONTAINER/Information)
        
        [ $(docker stop "$NOMECONTAINER") ] && {
          docker rm "$NOMECONTAINER"

          create
        } || {
          create
        }
        
      } || {
        docker stop "$NOMECONTAINER"
        docker rm "$NOMECONTAINER"
        
        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$NOMECONTAINER-$datetime.zip" -r /srv/containers/$NOMECONTAINER
        
        rm -R /srv/containers/"$NOMECONTAINER"

        menu
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    menu
    }
}

function menu {
  export var1; export var2; export var3

  VALUE1=""; VALUE2=""; VALUE3="/srv/containers/$NOMECONTAINER"

  VALUE0=$(dialog --ok-label "Criar" --title "Novo Container" --form "Containers: $NOMECONTAINER & $NOMECONTAINER-dns" 10 40 0 \
"Cache IP:" 1 1 "$VALUE1" 1 10 20 0 \
"LocalDNS:" 2 1 "$VALUE2" 2 10 20 0 \
"Cch PATH:" 3 1 "$VALUE3" 3 10 40 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  var2=$(echo "$VALUE0" | sed -n 2p)
  var3=$(echo "$VALUE0" | sed -n 3p)
  
  [ -z "$var1" ] || [ -z "$var2" ] && {
    dialog --title "ERRO" --msgbox "Não deixe nenhum campo vazio!" 8 40
    menu
  } || {
    create
    }
}

function create {
  export var1; export var2
  
  mkdir -p /srv/containers/"$NOMECONTAINER"
  touch /srv/containers/"$NOMECONTAINER"/Information
  echo "$var1" > /srv/containers/"$NOMECONTAINER"/Information
  echo "$var2" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var3" >> /srv/containers/"$NOMECONTAINER"/Information
  
  docker run -d \
--name="$NOMECONTAINER-dns" \
--hostname="$NOMECONTAINER-dns" \
--network macvlan \
--ip=$var1 \
--no-healthcheck \
--restart unless-stopped \
-p 53:53/udp \
-e USE_GENERIC_CACHE=true \
-e LANCACHE_IP=$var1 \
-e UPSTREAM_DNS=$var2 \
-v /etc/localtime:/etc/localtime:ro \
lancachenet/lancache-dns:latest

  docker run -d \
--name=$NOMECONTAINER \
--hostname="$NOMECONTAINER" \
--network macvlan \
--ip=$var1 \
--no-healthcheck \
--restart unless-stopped \
-p 80:80 \
-p 443:443 \
-e CACHE_INDEX_SIZE=512m \
-e CACHE_MAX_AGE=7d \
-e CACHE_DISK_SIZE=10000m \
-e CACHE_SLICE_SIZE=8m \
-v /etc/localtime:/etc/localtime:ro \
-v "$var3"/data:/data/cache \
-v /srv/containers/"$NOMECONTAINER"/logs:/data/logs \
lancachenet/monolithic:latest
}

function clean {
  unset var1
  unset var2
}

# Start
checkA
checkB
clean

exit
