#!/bin/bash

NOMECONTAINER="sms-powerview"

docker_repo="urbancompasspony/sms_powerview"
imagem="nobreak-sms"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="password"
CustmN5=""
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="p4ssw0rd"
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/$NOMECONTAINER/config
  wget https://cs.linuxuniverse.com.br/public.php/dav/files/7qpGCfAJk7ddSg7/install_sms.tar.gz
  tar -xvzf install_sms.tar.gz -C /srv/containers/$NOMECONTAINER/config
  rm install_sms.tar.gz
  
  sudo mv /srv/containers/$NOMECONTAINER/config/sms_powerview/* /srv/containers/$NOMECONTAINER/config/
  sudo rm -R /srv/containers/$NOMECONTAINER/config/sms_powerview
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    --device=/dev/ttyUSB0 \
    -p 8080:8080 -p 15000:15000 \
    -e PASS="$VALUE4" \
    -v /srv/containers/"$NOMECONTAINER"/config:/SMS \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  --device=/dev/ttyUSB0 \
  -e PASS="$VALUE4" \
  -v /srv/containers/"$NOMECONTAINER"/config:/SMS \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

execute_main

exit 0
