#!/bin/bash

NOMECONTAINER="luanti-server"

docker_repo="lscr.io/linuxserver/luanti:latest"
imagem="luanti"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="parameters"
CustmN5=""
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="--gameid minetest --terminal"
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/config/games/minetest_game
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --shm-size=256m \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -p 30000:30000/udp \
    -e PUID=1000 -e PGID=1000 \
    -e CLI_ARGS="$VALUE4" \
    -v /srv/containers/"$NOMECONTAINER"/config:/config/.minetest \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --shm-size=256m \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e PUID=1000 -e PGID=1000 \
  -e CLI_ARGS="$VALUE4" \
  -v /srv/containers/"$NOMECONTAINER"/config:/config/.minetest \
  "$docker_repo"

}

function docker_extras {
  if ! [ -d /srv/containers/"$NOMECONTAINER"/config/games/minetest_game/mods/ ]; then
    wget https://content.luanti.org/packages/Luanti/minetest_game/releases/29922/download/ -O /home/administrador/minetest_game.zip
    sudo unzip minetest_game.zip -d /srv/containers/"$NOMECONTAINER"/config/games
    sudo rm /home/administrador/minetest_game.zip

    sudo rm /srv/containers/"$NOMECONTAINER"/config/main-config/minetest.conf
    wget https://raw.githubusercontent.com/urbancompasspony/docker_custom/refs/heads/main/Config/minetest.conf -O /srv/containers/"$NOMECONTAINER"/config/main-config/minetest.conf
  fi
:; }

execute_main

exit 0
