#!/bin/bash

NOMECONTAINER="tailscale-node"

docker_repo="tailscale/tailscale:latest"
imagem="tailscale"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="advertise"
CustmN5="server"
CustmN6="auth_key"
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="0.0.0.0/24"
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/config
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --cap-add=NET_ADMIN --cap-add=NET_RAW \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e "TS_USERSPACE=0" \
    -e "TS_STATE_DIR=/var/lib/tailscale" \
    -e "TS_EXTRA_ARGS=--login-server=$VALUE5" \
    -e "TS_AUTHKEY=$VALUE6" \
    -v /dev/net/tun:/dev/net/tun \
    -v /srv/containers/"$NOMECONTAINER"/config:/var/lib/tailscale \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --cap-add=NET_ADMIN --cap-add=NET_RAW \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e "TS_USERSPACE=0" \
  -e "TS_STATE_DIR=/var/lib/tailscale" \
  -e "TS_EXTRA_ARGS=--login-server=$VALUE5" \
  -e "TS_AUTHKEY=$VALUE6" \
  -v /dev/net/tun:/dev/net/tun \
  -v /srv/containers/"$NOMECONTAINER"/config:/var/lib/tailscale \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

execute_main

exit 0
