#!/bin/bash

https://docs.linuxserver.io/images/docker-chrome/
docker run -d \
  --name=chrome \
  --security-opt seccomp=unconfined `#optional` \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e CHROME_CLI=https://www.linuxserver.io/ `#optional` \
  -p 3000:3000 \
  -p 3001:3001 \
  -v /path/to/config:/config \
  --shm-size="1gb" \
  --restart unless-stopped \
  lscr.io/linuxserver/chrome:latest



NOMECONTAINER="chromium-web-browser"

docker_repo="lscr.io/linuxserver/chromium:latest"
imagem="chromium-browser"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="custom_url"
CustmN5="path_dir"
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="google.com"
VALUE5="/srv/containers/$NOMECONTAINER/data"
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"
  sudo mkdir -p "$VALUE5"
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    --security-opt seccomp=unconfined \
    --shm-size="1gb" \
    -p 3000:3000 -p 3001:3001 \
    -e CHROME_CLI="$VALUE4" \
    -e PUID=1000 -e PGID=1000 \
    -v $VALUE5:/config \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  --security-opt seccomp=unconfined \
  --shm-size="1gb" \
  -e CHROME_CLI="$VALUE4" \
  -e PUID=1000 -e PGID=1000 \
  -v $VALUE5:/config \
  "$docker_repo"
}

function docker_extras {

:; }

check_root
check_macvlan
lockfile0

exit 0
