#!/bin/bash

NOMECONTAINER="qbittorrent"

docker_repo="lscr.io/linuxserver/qbittorrent:latest"
imagem="qbittorrent"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="downloads"
CustmN5="port"
CustmN6="torrent"
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="/mnt/disk01/downloads"
VALUE5="8060"
VALUE6="6881"
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/config
  sudo mkdir -p "$VALUE4"
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e PUID=1000 -e PGID=1000 \
    -e WEBUI_PORT="$VALUE5" \
    -e TORRENTING_PORT="$VALUE6" \
    -p "$VALUE5":"$VALUE5" -p "$VALUE6":"$VALUE6" -p "$VALUE6":"$VALUE6"/udp \
    -v /srv/containers/"$NOMECONTAINER"/config:/config \
    -v "$VALUE4":/downloads \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e PUID=1000 -e PGID=1000 \
  -e WEBUI_PORT="$VALUE5" \
  -e TORRENTING_PORT="$VALUE6" \
  -v /srv/containers/"$NOMECONTAINER"/config:/config \
  -v "$VALUE4":/downloads \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

execute_main

exit 0
