#!/bin/bash

NOMECONTAINER="plocate-web"

docker_repo="urbancompasspony/plocate"
imagem="plocate"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="WEB_USERNAME"
CustmN5="WEB_PASSWORD"
CustmN6="PATH_DATA"
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="admin"
VALUE5="p4ss0rd"
VALUE6="/mnt"
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/database
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e WEB_USERNAME="$VALUE4" \
    -e WEB_PASSWORD="$VALUE5" \
    -p 80:80 \
    -v /srv/containers/"$NOMECONTAINER"/database:/var/lib/plocate \
    -v "$VALUE6":/data:ro \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e WEB_USERNAME="$VALUE4" \
  -e WEB_PASSWORD="$VALUE5" \
  -v /srv/containers/"$NOMECONTAINER"/database:/var/lib/plocate \
  -v "$VALUE6":/data:ro \
  "$docker_repo"
}

function docker_extras {
  clear ; echo "" ; echo "Indexando arquivos..."
  docker exec $NOMECONTAINER updatedb
  clear; echo "Use it on crontab: 0 7 * * * docker exec $NOMECONTAINER updatedb"
:; }

execute_main

exit 0
