#!/bin/bash

# Global config for replication:
export NOMECONTAINER="collabora"

# IP FIXO DO NOVO CONTAINER
export var1

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}
   create
    }
}

function checkB {
  export var1; export var2

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    dialog --title "Dados de $NOMECONTAINER encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $NOMECONTAINER" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)

        [ $(docker stop "$NOMECONTAINER") ] && {
          docker rm "$NOMECONTAINER"
          create
        } || {
          create
        }

      } || {
        docker stop "$NOMECONTAINER"
        docker rm "$NOMECONTAINER"

        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$NOMECONTAINER-$datetime.zip" -r /srv/containers/$NOMECONTAINER

        rm -iR /srv/containers/"$NOMECONTAINER"

        menu
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    menu
    }
}

function menu {
  export var1

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    VALUE1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)
  } || {
    VALUE1=""
  }

  VALUE0=$(dialog --ok-label "Criar" --title "Container: $NOMECONTAINER" --form "" 8 40 0 \
"Local IP:" 1 1 "$VALUE1" 1 10 20 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  
  [ -z "$var1" ] && {
    dialog --title "ERRO" --msgbox "Não deixe nenhum campo vazio!" 8 40
    menu
  } || {
    checkC
    }
}

function checkC {
  #IPMachine=$(hostname -I | awk '{print $1}')
  MyIP=$(cat /srv/containers/scripts/myip)
  [ "$MyIP" = "$var1" ] && {
    dialog --title "ERRO" --msgbox "Conflito de IP detectado! \nMude para outro IP." 6 40
    menu
  } || {
    create
  }
}

function create {
  export var1

  mkdir -p /srv/containers/"$NOMECONTAINER"

  touch /srv/containers/"$NOMECONTAINER"/Information
  echo "$var1" > /srv/containers/"$NOMECONTAINER"/Information

docker run -d \
--name=$NOMECONTAINER \
--network macvlan \
--ip=$var1 \
--dns=1.1.1.1  \
--dns=127.0.0.1 \
--hostname=$NOMECONTAINER \
--restart=unless-stopped \
--no-healthcheck \
-p 9980:9980 \
-e username="admin" \
-e password="P4ssw0rd" \
-e "extra_params=--o:ssl.enable=false --o:ssl.termination=false" \
-v /etc/localtime:/etc/localtime:ro \
collabora/code
}

# IF NOT USING SSL!
# -e extra_params="--o:ssl.enable=false" \

function clean {
  unset var1
}

# Start
checkA
checkB

sleep 5

echo "============================"
echo "# # # Testing HTTP :80 # # #"
echo "============================"
docker exec $NOMECONTAINER curl -k http://$var1:9980
echo " "
echo "=============================="
echo "# # # Testing HTTPS :443 # # #"
echo "============================="
docker exec $NOMECONTAINER curl -k https://$var1:9980
echo " "

clean

exit
