#!/bin/bash

# Nextcloud Version!
nv="25"

#############################################################################################################

# Some notes:

# DOES NOT PUT ANY PORTS ON -p FLAG FOR THIS CONTAINER!
# IF YOU DO SO, WILL CONFLICT WITH MYSQL CONTAINER THROUGH BRIDGE NETWORK.

# Do it too after migrating:

# Change /data permissions set as root user: sudo -i
# chown www-data:www-data -R /mnt/data

# find /mnt/data -type f -print0 | xargs -0 chmod 0640
# find /mnt/data -type d -print0 | xargs -0 chmod 0750

# Inside Container:

# docker exec -it nextcloud bash
# php occ maintenance:theme:update

# SET MAINTENANCE OFF!

# docker exec -u www-data -it nextcloud bash
# php occ files:scan --all

# Outside container:

# Set this on Cron's Host:
# */5 * * * * docker exec -t -u www-data nextcloud php -f /var/www/html/cron.php
# 00 01 01 * * docker exec nextcloud certbot --apache renew
# Will auto renew SSL once a month and run cron.php when needed.

# The End!

#############################################################################################################

# Global config for replication:
export NOMECONTAINER="nextcloud"

# IP FIXO DO NOVO CONTAINER
export var1; export var2; export var3

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function checkB {
  export var1; export var2; export var3

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    dialog --title "Dados de $NOMECONTAINER encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $NOMECONTAINER" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)
        var2=$(sed -n '2p' /srv/containers/$NOMECONTAINER/Information)
        var3=$(sed -n '3p' /srv/containers/$NOMECONTAINER/Information)

        [ $(docker stop "$NOMECONTAINER") ] && {
          docker rm "$NOMECONTAINER"
          create
        } || {
          create
        }

      } || {
        docker stop "$NOMECONTAINER"
        docker rm "$NOMECONTAINER"

        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$NOMECONTAINER-$datetime.zip" -r /srv/containers/$NOMECONTAINER

        rm -iR /srv/containers/"$NOMECONTAINER"

        menu
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    menu
    }
}

function menu {
  export var1; export var2; export var3

  VALUE1=""; VALUE2="/srv/containers/$NOMECONTAINER"; VALUE3="cloud.my-website.com"

  VALUE0=$(dialog --ok-label "Criar" --title "Container: $NOMECONTAINER" --form "Campo NxtData: VAR/data autopreenchido! \nDefina 1 diretório abaixo e sem /." 12 40 0 \
"Local IP:" 1 1 "$VALUE1" 1 10 20 0 \
"Nxt Data:" 2 1 "$VALUE2" 2 10 40 0 \
"URL WAN :" 3 1 "$VALUE3" 3 10 50 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  var2=$(echo "$VALUE0" | sed -n 2p)
  var3=$(echo "$VALUE0" | sed -n 3p)

  [ -z "$var1" ] || [ -z "$var2" ] || [ -z "$var3" ] && {
    dialog --title "ERRO" --msgbox "Não deixe nenhum campo vazio!" 8 40
    menu
  } || {
    create
    }
}

function create {
  export var1; export var2; export var3

  mkdir -p /srv/containers/"$NOMECONTAINER"
  mkdir -p "$var2"

  touch /srv/containers/"$NOMECONTAINER"/Information
  echo "$var1" > /srv/containers/"$NOMECONTAINER"/Information
  echo "$var2" >> /srv/containers/"$NOMECONTAINER"/Information
  echo "$var3" >> /srv/containers/"$NOMECONTAINER"/Information

docker run -d \
--name=$NOMECONTAINER \
--network macvlan \
--ip=$var1 \
--dns=1.1.1.1  \
--dns=127.0.0.1 \
--hostname=nextcloud \
--restart=unless-stopped \
--no-healthcheck \
-v /etc/localtime:/etc/localtime:ro \
-v /srv/containers/"$NOMECONTAINER"/config:/var/www/html/config \
-v "$var2"/data:/var/www/html/data \
nextcloud:"$nv"
}

function clean {
  unset var1
  unset var2
  unset var3
}

# Start
checkA
checkB

docker network connect bridge $NOMECONTAINER

# Some scripts to run after installation
docker exec nextcloud apt update
docker exec nextcloud apt install smbclient nano -y
docker exec nextcloud apt install certbot python3-certbot-apache -y

# Generate a new SSL certificate!
docker exec -it nextcloud bash certbot --apache -d "$var3" -m josehumbertoferreirajunior@gmail.com --agree-tos

# Manually:
# Inside container creating a Let's Encrypt SSL:
# docker exec -it nextcloud bash
# certbot --apache -d seu-site.com

docker restart nextcloud

# AutoSet Crontab:
sudo crontab -l > /tmp/crontab
echo "# AutoRenew and Nextcloud Maintenance" | tee -a /tmp/crontab
echo "*/5 * * * * docker exec -t -u www-data nextcloud php -f /var/www/html/cron.php" | tee -a /tmp/crontab
echo "00 01 01 * * docker exec nextcloud certbot --apache renew" | tee -a /tmp/crontab
sudo crontab /tmp/crontab

clean

exit
