#!/bin/bash

NOMECONTAINER="docker-macosx"

docker_repo="sickcodes/docker-osx:latest"
imagem="docker-macos"

CustmN2="vnc_port"
CustmN3="ssh_port"
CustmN4="shortname"
CustmN5="ram_gb"
CustmN6="cpu_cores"
CustmN7="disk_size"
CustmN8="extra_params"
CustmN9=""
CustmN10=""

# Valores padrão
VALUE2="5901"
VALUE3="50922"
VALUE4="sonoma high-sierra mojave catalina big-sur monterey ventura"
VALUE5="8"
VALUE6="6"
VALUE7="256G"
VALUE8="-display none -vnc 0.0.0.0:1"
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/OSX-KVM
  sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --device /dev/kvm \
    --network host \
    --no-healthcheck --restart=unless-stopped \
    -v /etc/localtime:/etc/localtime:ro \
    -p "$VALUE2:5901" \
    -p "$VALUE3:10022" \
    -e SHORTNAME="$VALUE4" \
    -e RAM="$VALUE5" \
    -e CORES="$VALUE6" \
    -e SIZE="$VALUE7" \
    -e EXTRA="$VALUE8" \
    -v "/srv/containers/$NOMECONTAINER/OSX-KVM:/home/arch/OSX-KVM" \
    "$docker_repo"

    return
  fi

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --device /dev/kvm \
    --network host \
    --no-healthcheck --restart=unless-stopped \
    -v /etc/localtime:/etc/localtime:ro \
    -p "$VALUE2:5901" \
    -p "$VALUE3:10022" \
    -e SHORTNAME="$VALUE4" \
    -e RAM="$VALUE5" \
    -e CORES="$VALUE6" \
    -e SIZE="$VALUE7" \
    -e EXTRA="$VALUE8" \
    -v "/srv/containers/$NOMECONTAINER/OSX-KVM:/home/arch/OSX-KVM" \
    "$docker_repo"
}

function docker_extras {
  clear
  echo "REMMINA:"
  echo "VNC: localhost:5901"
  sleep 5
:; }

execute_main

exit 0
