#!/bin/bash

sudo apt install linux-modules-extra-$(uname -r)
sudo apt install adb
sudo apt install scrcpy

sudo modprobe binder_linux devices="binder,hwbinder,vndbinder"
sudo modprobe ashmem_linux

docker run -it --rm --privileged \
    --pull always \
    -v /srv/containers/redroid:/data \
    -p 5555:5555 \
    redroid/redroid:13.0.0-latest

adb connect localhost:5555

scrcpy -s localhost:5555
# https://github.com/remote-android/redroid-doc

docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_14.0

