#!/bin/bash

# Global config for replication:
export NOMECONTAINER="reverseproxy"

# IP FIXO DO NOVO CONTAINER
export var1

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function checkB {
  export var1

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    dialog --title "Dados de $NOMECONTAINER encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $NOMECONTAINER" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)
        
        [ $(docker stop "$NOMECONTAINER") ] && {
          docker rm "$NOMECONTAINER"

          create
        } || {
          create
        }
        
      } || {
        docker stop "$NOMECONTAINER"
        docker rm "$NOMECONTAINER"
        
        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$NOMECONTAINER-$datetime.zip" -r /srv/containers/$NOMECONTAINER
        
        rm -iR /srv/containers/"$NOMECONTAINER"

        menu
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    menu
    }
}

function menu {
  export var1

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    VALUE1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)
  } || {
    VALUE1=""
  }

  VALUE0=$(dialog --ok-label "Criar" --title "Novo Container" --form "Container: $NOMECONTAINER" 10 40 0 \
"Local IP: " 1 1 "$VALUE1" 1 10 20 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  
  [ -z "$var1" ] && {
    dialog --title "ERRO" --msgbox "Não deixe nenhum campo vazio!" 8 40
    menu
  } || {
    checkC
    }
}

function checkC {
  #IPMachine=$(hostname -I | awk '{print $1}')
  MyIP=$(cat /srv/containers/scripts/myip)
  [ "$MyIP" = "$var1" ] && {
    dialog --title "ERRO" --msgbox "Conflito de IP detectado! \nMude para outro IP." 6 40
    menu
  } || {
    create
  }
}

function create {
  export var1
  
  mkdir -p /srv/containers/"$NOMECONTAINER"/apache2/sites-available
  mkdir -p /srv/containers/"$NOMECONTAINER"/apache2/sites-enabled
  mkdir -p /srv/containers/"$NOMECONTAINER"/certbot
  
  touch /srv/containers/"$NOMECONTAINER"/Information
  echo "$var1" > /srv/containers/"$NOMECONTAINER"/Information

docker run -d \
  --name=$NOMECONTAINER \
  --network macvlan \
  --ip=$var1 \
  --dns=1.1.1.1  \
  --dns=127.0.0.1 \
  --no-healthcheck \
  --restart unless-stopped \
  -p 80:80 \
  -p 443:443 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /srv/containers/"$NOMECONTAINER"/apache2/sites-available:/etc/apache2/sites-available \
  -v /srv/containers/"$NOMECONTAINER"/apache2/sites-enabled:/etc/apache2/sites-enabled \
  -v /srv/containers/"$NOMECONTAINER"/certbot:/etc/letsencrypt \
  urbancompasspony/reverseproxy:latest
  }

function clean {
  unset var1
}

# Start
checkA
checkB
clean

echo " "
echo "Re-deploy existent certificates if re-running this script:"
echo "docker exec reverseproxy certbot install --cert-name myweb-site.com"
echo " "
echo "To generate NEW certificates:"
echo "docker exec reverseproxy certbot --apache --non-interactive -m myemail@myprovider.com --agree-tos --domain myweb-site.com"
echo "docker exec reverseproxy certbot install --cert-name myweb-site.com"
echo " "
echo "Get a Model.conf for Proxy here:"
echo "curl -sSL https://raw.githubusercontent.com/urbancompasspony/docker/main/Custom_Images/reverseproxy/model > model.conf"
echo "Use NANO inside container to set /sites-available/ and create a link to /sites-enabled/"
echo "docker exec -it reverseproxy bash"
echo "Restart container to validate"
echo " "
echo "Force Renew:"
echo "certbot --apache renew"
echo "Container has his own renew script, but use this crontab on Host if needed:"
echo "* * 01 * * docker exec reverseproxy certbot --apache renew"

exit 1
