#!/bin/bash

# To use on Website directly!

# To use inside Nextcloud, do not use this container;
# Instead, install "onlyoffice connector" and "community office server" apps.

# Global config for replication:
export NOMECONTAINER="onlyoffice"

# IP FIXO DO NOVO CONTAINER
export var1

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root!"
    exit
    }
}

function checkB {
  export var1; export var2

  [ -f "/srv/containers/$NOMECONTAINER/Information" ] && {
    dialog --title "Dados de $NOMECONTAINER encontrados!" --yesno "Deseja refazer o container?" 6 40
    [ $? = 0 ] && {
    dialog --title "Recriando o container $NOMECONTAINER" --yesno "Deseja reaproveitar os DADOS da instalação anterior?" 6 40
      [ $? = 0 ] && {
        var1=$(sed -n '1p' /srv/containers/$NOMECONTAINER/Information)

        [ $(docker stop "$NOMECONTAINER") ] && {
          docker rm "$NOMECONTAINER"
          create
        } || {
          create
        }

      } || {
        docker stop "$NOMECONTAINER"
        docker rm "$NOMECONTAINER"

        datetime=$(date +"%d-%m %H-%M")
        mkdir -p /srv/containers/.backupcnt
        zip "/srv/containers/.backupcnt/$NOMECONTAINER-$datetime.zip" -r /srv/containers/$NOMECONTAINER

        rm -iR /srv/containers/"$NOMECONTAINER"

        menu
        }
    } || {
      echo "A instalação local será mantida! Saindo..."
      exit
    }
  } || {
    menu
    }
}

function menu {
  export var1

  VALUE1=""

  VALUE0=$(dialog --ok-label "Criar" --title "Container: $NOMECONTAINER" --form "" 8 40 0 \
"Local IP:" 1 1 "$VALUE1" 1 10 20 0 \
3>&1 1>&2 2>&3 3>&- > /dev/tty)

  [ $? -ne 0 ] && exit
  var1=$(echo "$VALUE0" | sed -n 1p)
  
  [ -z "$var1" ] && {
    dialog --title "ERRO" --msgbox "Não deixe nenhum campo vazio!" 8 40
    menu
  } || {
    checkC
    }
}

function checkC {
  #IPMachine=$(hostname -I | awk '{print $1}')
  MyIP=$(cat /srv/containers/scripts/myip)
  [ "$MyIP" = "$var1" ] && {
    dialog --title "ERRO" --msgbox "Conflito de IP detectado! \nMude para outro IP." 6 40
    menu
  } || {
    create
  }
}

function create {
  docker pull onlyoffice/documentserver
  export var1; mkdir -p /srv/containers/"$NOMECONTAINER"
  touch /srv/containers/"$NOMECONTAINER"/Information
  echo "$var1" > /srv/containers/"$NOMECONTAINER"/Information

JWT_SECRET_0=$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 12)

docker run -d \
--name=$NOMECONTAINER \
--network macvlan \
--ip=$var1 \
--dns=1.1.1.1  \
--dns=127.0.0.1 \
--hostname=$NOMECONTAINER \
--restart=unless-stopped \
--no-healthcheck \
-e JWT_SECRET="$JWT_SECRET_0" \
-p 80:80 \
-v /etc/localtime:/etc/localtime:ro \
-v /srv/containers/"$NOMECONTAINER"/logs:/var/log/onlyoffice  \
-v /srv/containers/"$NOMECONTAINER"/data:/var/www/onlyoffice/Data \
-v /srv/containers/"$NOMECONTAINER"/lib:/var/lib/onlyoffice \
-v /srv/containers/"$NOMECONTAINER"/postgresql:/var/lib/postgresql \
-v /srv/containers/"$NOMECONTAINER"/fonts:/usr/share/fonts/truetype/custom \
onlyoffice/documentserver
}

function extras {
echo "==================================================================================================================="

echo ""
echo "Generating JWT Secret.... Your Token is:"
echo ""
echo $JWT_SECRET_0 | sudo tee /srv/containers/"$NOMECONTAINER"/secret
echo ""
echo "==================================================================================================================="
echo ""
echo "If you pretend to set it on NextCloud:"
echo "ONLYOFFICE Docs Address:"
echo "Address of OnlyOffice Docker Service with SSL, example: https://officeserver.ddns.net/ with a / at the end!"
echo "Server Address for internal requests:"
echo "The FQDN of the Nextcloud Server, example: https://myserver.ddns.net/ with a / at the end!"
echo ""
echo "FQDN not acessible on LAN! On this case, will be acessible only through IP."
echo "To have a FQDN create a server on another IP Address."
echo ""
echo "If OnlyOffice will be direct on 80:443 ports of Firewall, run this command and put it on cron:"
echo "* 10 * * * docker exec onlyoffice bash /usr/bin/documentserver-letsencrypt.sh goodfriendadvice@protonmail.com MY_WEBSITE.ddns.net"
echo ""
echo "If behind a ReverseProxy, generate certificate normally only on Reverse Proxy, not inside Container."
echo "Then, edit /sites-enabled/office.conf and add as here:"
echo "https://raw.githubusercontent.com/urbancompasspony/docker/main/Apache2/https-to-http"
echo ""
echo "Integrated editor (TEST ONLY!):"
echo "sudo docker exec $NOMECONTAINER sudo supervisorctl start ds:example"
echo ""
echo "==================================================================================================================="

sleep 10

}

function clean {
  unset JWT_SECRET_0
  unset JWT_SECRET
  unset var1
}

# Start
checkA
checkB
extras
clean
docker image prune -af
exit 1
