#!/bin/bash

JWT_SECRET_0=$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 12)

NOMECONTAINER="onlyoffice-server"

docker_repo="onlyoffice/documentserver"
imagem="onlyoffice"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="secret"
CustmN5=""
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="$JWT_SECRET_0"
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/{logs,data,lib,postgresql,fonts}
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host -p 80:80 \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e JWT_SECRET="$VALUE4" \
    -v /srv/containers/"$NOMECONTAINER"/logs:/var/log/onlyoffice  \
    -v /srv/containers/"$NOMECONTAINER"/data:/var/www/onlyoffice/Data \
    -v /srv/containers/"$NOMECONTAINER"/lib:/var/lib/onlyoffice \
    -v /srv/containers/"$NOMECONTAINER"/postgresql:/var/lib/postgresql \
    -v /srv/containers/"$NOMECONTAINER"/fonts:/usr/share/fonts/truetype/custom \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e JWT_SECRET="$VALUE4" \
  -v /srv/containers/"$NOMECONTAINER"/logs:/var/log/onlyoffice  \
  -v /srv/containers/"$NOMECONTAINER"/data:/var/www/onlyoffice/Data \
  -v /srv/containers/"$NOMECONTAINER"/lib:/var/lib/onlyoffice \
  -v /srv/containers/"$NOMECONTAINER"/postgresql:/var/lib/postgresql \
  -v /srv/containers/"$NOMECONTAINER"/fonts:/usr/share/fonts/truetype/custom \
  "$docker_repo"
}

function docker_extras {
  clear
  echo "==================================================================================================================="
  echo ""
  echo "Your Token is:"
  echo ""
  echo $VALUE4 | sudo tee /srv/containers/"$NOMECONTAINER"/secret
  echo ""
  echo "==================================================================================================================="
  echo ""
  echo "If OnlyOffice will be direct on 80:443 ports of Firewall, run this command and put it on cron:"
  echo "* 10 * * * docker exec onlyoffice bash /usr/bin/documentserver-letsencrypt.sh goodfriendadvice@protonmail.com MY_WEBSITE.ddns.net"
  echo ""
  echo "Integrated editor (TEST ONLY!):"
  echo "sudo docker exec $NOMECONTAINER sudo supervisorctl start ds:example"
  echo ""
  echo "==================================================================================================================="
  sleep 10
:; }

check_root
check_macvlan
lockfile0

exit 0
