#!/bin/bash

NOMECONTAINER="ftp-server"

docker_repo="bogem/ftp"
imagem="ftp"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="shr_name"
CustmN5="mnt_path"
CustmN6="username"
CustmN7="password"
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="ftp-srv"
VALUE5="-v /mnt:/home/vsftpd"
VALUE6="admin"
VALUE7="p4ssw0rd"
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -p 20:20 -p 21:21 -p 47400-47470:47400-47470 \
    -e FTP_USER="$VALUE6" -e FTP_PASS="$VALUE7" -e PASV_ADDRESS="$VALUE2" \
    -v "/srv/containers/$NOMECONTAINER/config:/config" \
    -v "/srv/containers/$NOMECONTAINER/data:/data" \
    $VALUE5 \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e FTP_USER="$VALUE6" -e FTP_PASS="$VALUE7" -e PASV_ADDRESS="$VALUE2" \
  -v "/srv/containers/$NOMECONTAINER/config:/config" \
  -v "/srv/containers/$NOMECONTAINER/data:/data" \
  $VALUE5 \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

check_root
check_macvlan
lockfile0

exit 0
