#!/bin/bash

NOMECONTAINER="ssh-dw"
docker_repo="urbancompasspony/ssh-dw:latest"
base_img="dwservice"
set_folders="data"

CustmN2="LocalIP"
CustmN3="teste01"
CustmN4="."
CustmN5="."
CustmN6="."
CustmN7="."
CustmN8="."
CustmN9="."
CustmN10="."

VALUE2="HOSTONLY"
VALUE3="aaa"
VALUE4="0"
VALUE5="0"
VALUE6="0"
VALUE7="0"
VALUE8="0"
VALUE9="0"
VALUE10="0"

function docker_create {
docker run -d --privileged --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network host --add-host=host.docker.internal:host-gateway \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -v /srv/containers/"$NOMECONTAINER"/data:/usr/share \
  "$docker_repo"

#--privileged
#--network host --add-host=host.docker.internal:host-gateway \
}

# USE IT ONLY IF NEEDED:
function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"

echo "0" > /dev/null
}

source <(curl -fsSL https://raw.githubusercontent.com/urbancompasspony/docker/refs/heads/main/X-base-source.sh)

check_root
check_macvlan
lockfile0

exit 0
