#!/bin/bash

NOMECONTAINER="ssh-dw"

docker_repo="urbancompasspony/ssh-dw:latest"
service="dwservice"
set_mkdir="data"

CustmN2="LocalIP"
CustmN3="."
CustmN4="."
CustmN5="."
CustmN6="."
CustmN7="."
CustmN8="."
CustmN9="."
CustmN10="."

VALUE2="HOSTONLY"
VALUE3="0"
VALUE4="0"
VALUE5="0"
VALUE6="0"
VALUE7="0"
VALUE8="0"
VALUE9="0"
VALUE10="0"

function docker_create {
docker run -d --privileged --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network host --add-host=host.docker.internal:host-gateway \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -v /srv/containers/"$NOMECONTAINER"/data:/usr/share \
  "$docker_repo"

# Examples
# PATH: $VALUE3 \
# -e variavel1="$VALUE4" \
# --privileged
# --network host --add-host=host.docker.internal:host-gateway \
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

masterfile="/srv/system.yaml"
configfile="/srv/containers.yaml"

labels=("Nome_Custom" "$CustmN2" "$CustmN3" "$CustmN4" "$CustmN5" "$CustmN6" "$CustmN7" "$CustmN8" "$CustmN9" "$CustmN10")

values=("$NOMECONTAINER" "$VALUE2" "$VALUE3" "$VALUE4" "$VALUE5" "$VALUE6" "$VALUE7" "$VALUE8" "$VALUE9" "$VALUE10")

function check_root {
  [ "$EUID" -ne 0 ] && {
    echo "Execute esse script como Root! Saindo..."
    exit 1
  }
}

function check_macvlan {
  if ! docker inspect macvlan 1>/dev/null 2>/dev/null; then
    echo "A macvlan não existe! Saindo..."; sleep 3
    exit 0
  fi
}

function try_pull {
  if ! docker pull "$docker_repo"; then
    echo "Erro: docker pull falhou... saindo."; sleep 3
    exit 1
  fi
}

function lockfile0 {
  if [ -f /srv/lockfile ]; then
    load_config_check
    try_pull
    docker_create
    docker_extras
    save_config
  else
    main_menu
  fi
}

function load_config_check {
  if ! [ -f "$configfile" ]; then
    echo ""; echo "ERRO CRITICO: NAO ENCONTREI O $configfile! Saindo."
    exit 1
  elif grep -qw "$NOMECONTAINER" "$configfile"; then
    load_data
  else
    echo ""; echo "ERRO: NAO ENCONTREI DADOS SUFICIENTES EM $configfile! Saindo."
    exit 1
  fi
}

function load_data {
  if ! [ -f "$configfile" ]; then
    return
  fi

  if [ "$(grep -c -w "$service" "$configfile")" -gt 1 ]; then
    LISTANOMES=$(yq -r 'to_entries[].value.Nome_Custom' "$configfile")
    NOMECONTAINER=$(dialog --title "Imagem detectada: $service" --backtitle "W A R N I N G" --ok-button "Carregar" --no-cancel --inputbox "Encontrei mais de um container registrado com essa imagem! Qual deseja carregar?\nValores encontrados:\n$LISTANOMES" 0 0 "" 2>&1 > /dev/tty)
  fi

  for i in "${!labels[@]}"; do
    val="$(yq -r '.["'"$NOMECONTAINER"'"].["'"${labels[$i]}"'"]' "$configfile")"
    if [[ "$val" == "null" || -z "$val" ]]; then
      eval "VALUE$((i+1))=\"${values[$i]}\""
      values[i]="${values[$i]}"
    else
      eval "VALUE$((i+1))=\"$val\""
      values[i]="$val"
    fi
  done

  if [ "$NOMECONTAINER" = "" ]; then
    dialog --title "WARNING" --msgbox "Campo vazio! Cuidado com a sobrescrita de dados!" 6 40
    button_ok0="Criar"
  else
    button_ok0="Recriar"
  fi
}

function save_config {
  sudo touch "$configfile"

  datetime0=$(date +"%d-%m-%Y_%H:%M")
  sudo yq -i ".\"${NOMECONTAINER}\".install = \"${datetime0}\"" "$configfile"
  sudo yq -i ".\"${NOMECONTAINER}\".baseimg = \"${service}\"" "$configfile"

  for i in "${!labels[@]}"; do
    sudo yq -i ".\"${NOMECONTAINER}\".\"${labels[$i]}\" = \"${values[$i]}\"" "$configfile"
  done
}

function main_menu {
  load_data

  form_args=()
  for idx in "${!labels[@]}"; do
    line=$((idx+1))
    form_args+=("${labels[$idx]}" "$line" 1 "${values[$idx]}" "$line" 17 150 0)
  done

  if ! form=$(dialog --ok-label "$button_ok0" --title "Novo Container" --form "Imagem Base: $service" 17 80 0 \
    "${form_args[@]}" 3>&1 1>&2 2>&3 3>&- > /dev/tty); then
    return
  fi

  mapfile -t VALUES <<< "$form"
  for i in {1..10}; do
    eval "VALUE$i=\"\${VALUES[$((i-1))]}\""
    values[i-1]="${VALUES[$((i-1))]}"
  done

  NOMECONTAINER="${VALUES[0]}"

  save_config
  check_IP
}

function check_IP {
  if [[ "${VALUE2,,}" =~ ^(LOCALONLY|HOSTONLY|ONLYLOCAL|ONLYHOST|localonly|hostonly|onlylocal|onlyhost|host|Host|HOST|local|Local|LOCAL|hostname|Hostname|HostName|HOSTNAME|localhost|Localhost|LocalHost|LOCALHOST|)$ ]]; then
    mkdir0
    try_pull
    docker_create
    docker_extras
    cleanup0
  else
    # Verifica conflito normalmente
    if grep -qw "$VALUE2" "$masterfile"; then
      dialog --title "ERRO" --msgbox "Conflito de IP detectado no $masterfile:\nMesmo IP do Host!" 6 40
      main_menu
    elif grep -qw "$VALUE2" "$configfile"; then
      dialog --title "ERRO" --msgbox "Conflito de IP detectado no $configfile:\nMesmo IP de outro container!" 6 40
      main_menu
    else
      mkdir0
      try_pull
      docker_create
      docker_extras
      cleanup0
    fi
  fi
}

function mkdir0 {
  if [ -d "/srv/containers/$NOMECONTAINER" ]; then
    if ! dialog --title "WARNING" --yes-label "Prosseguir" --no-label "CANCELAR" --yesno "Foram identificados dados previamente configurados! \n\nParando e removendo container caso esteja rodando. \n\nSe precisar, apague o conteudo de /srv/$NOMECONTAINER manualmente" 14 50; then
      exit 0
    fi

    if docker stop "$NOMECONTAINER"; then
      docker rm "$NOMECONTAINER"
      echo "O container $NOMECONTAINER estava executando, foi parado e removido. Continuando..."; sleep 1
    elif docker rm "$NOMECONTAINER"; then
      echo "O container $NOMECONTAINER nao estava executando e foi removido. Continuando..."; sleep 1
    else
      echo "O container $NOMECONTAINER nao existia, nao estava executando e/ou nao foi identificado. Continuando..."; sleep 1
    fi
  else
    mkdir -p /srv/containers/"$NOMECONTAINER"/"$set_mkdir"
  fi
}

function cleanup0 {
  for i in {1..10}; do
    unset "VALUE$i"
  done

  docker image prune -af

  for i in {1..10}; do
    unset "CustmN$i"
  done
}

check_root
check_macvlan
lockfile0

exit 0
