#!/bin/bash

NOMECONTAINER="homarr"

docker_repo="ghcr.io/ajnart/homarr:latest"
imagem="homarr-web-panel"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="porta"
CustmN5=""
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="80"
VALUE5=""
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/{configs,data,icons,backgrounds}
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
 
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -e PORT="$VALUE4" -p "$VALUE4":7575 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /srv/containers/"$NOMECONTAINER"/data:/data \
    -v /srv/containers/"$NOMECONTAINER"/icons:/app/public/icons \
    -v /srv/containers/"$NOMECONTAINER"/configs:/app/data/configs \
    -v /srv/containers/"$NOMECONTAINER"/backgrounds:/app/public/imgs/backgrounds \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e PORT="$VALUE4" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /srv/containers/"$NOMECONTAINER"/data:/data \
  -v /srv/containers/"$NOMECONTAINER"/icons:/app/public/icons \
  -v /srv/containers/"$NOMECONTAINER"/configs:/app/data/configs \
  -v /srv/containers/"$NOMECONTAINER"/backgrounds:/app/public/imgs/backgrounds \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

check_root
check_macvlan
lockfile0

exit 0
