#!/bin/bash

NOMECONTAINER="qdir-stat"

docker_repo="lscr.io/linuxserver/qdirstat:latest"
imagem="qdir"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="path:ro?"
CustmN5="username"
CustmN6="password"
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="/mnt:/data:ro"
VALUE5="admin"
VALUE6="p4ssw0rd"
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/config
  # sudo touch /srv/containers/"$NOMECONTAINER"/file
  # sudo chmod -R 777 /srv/containers/"$NOMECONTAINER"
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then
  
    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    -p 3000:3000 -p 3001:3001 \
    -e PUID=1000 -e PGID=1000 \
    -e CUSTOM_USER="$VALUE5" -e PASSWORD="$VALUE6" \
    -v /srv/containers/"$NOMECONTAINER"/config:/config \
    -v $VALUE4 \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  -e PUID=1000 -e PGID=1000 \
  -e CUSTOM_USER="$VALUE5" -e PASSWORD="$VALUE6" \
  -v /srv/containers/"$NOMECONTAINER"/config:/config \
  -v $VALUE4 \
  "$docker_repo"
}

function docker_extras {
  clear; echo ""
  echo "Access: https://$VALUE2:3001/"
  sleep 5
:; }

execute_main

exit 0
