#!/bin/bash

NOMECONTAINER="elastic-search"

docker_repo="docker.elastic.co/elasticsearch/elasticsearch:7.17.22"
imagem="elasticsearch-db"

CustmN2="local_ip"
CustmN3="servidor_dns"
CustmN4="memory_mb"
CustmN5="cpu"
CustmN6=""
CustmN7=""
CustmN8=""
CustmN9=""
CustmN10=""

VALUE2="0.0.0.0"
VALUE3="8.8.4.4"
VALUE4="2048m"
VALUE5="2"
VALUE6=""
VALUE7=""
VALUE8=""
VALUE9=""
VALUE10=""

export NOMECONTAINER docker_repo imagem
export CustmN2 CustmN3 CustmN4 CustmN5 CustmN6 CustmN7 CustmN8 CustmN9 CustmN10
export VALUE2 VALUE3 VALUE4 VALUE5 VALUE6 VALUE7 VALUE8 VALUE9 VALUE10

if [ -f /tmp/common-functions.sh ]; then
  source /tmp/common-functions.sh
else
  echo "ERRO: common-functions.sh não encontrado!"
  exit 1
fi

function set_mkdir {
  sudo mkdir -p /srv/containers/"$NOMECONTAINER"/data
  sudo sysctl -w vm.max_map_count=262144
  echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
:; }

function docker_create {
  local ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

  # Se NAO for numerico, execute como host!
  if [[ ! "$VALUE2" =~ $ip_regex ]]; then

    docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
    --network host \
    --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
    --ulimit memlock=-1:-1 --cpus="$VALUE5" -m "$VALUE4" \
    -p 9200:9200 \
    -e PUID=1000 -e PGID=1000 \
    -e discovery.type=single-node \
    -e xpack.security.enabled=false \
    -e bootstrap.memory_lock=true \
    -e "ES_JAVA_OPTS=-Xms1g -Xmx1g" \
    -v /srv/containers/"$NOMECONTAINER"/data:/data \
    "$docker_repo"

    return
  fi

  docker run -d --name="$NOMECONTAINER" --hostname="$NOMECONTAINER" \
  --network macvlan --ip="$VALUE2" --dns="$VALUE3" \
  --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
  --ulimit memlock=-1:-1 --cpus="$VALUE5" -m "$VALUE4" \
  -e PUID=1000 -e PGID=1000 \
  -e discovery.type=single-node \
  -e xpack.security.enabled=false \
  -e bootstrap.memory_lock=true \
  -e "ES_JAVA_OPTS=-Xms1g -Xmx1g" \
  -v /srv/containers/"$NOMECONTAINER"/data:/data \
  "$docker_repo"
}

function docker_extras {
#docker exec "$NOMECONTAINER" bash -c "echo 'parameter=0' >> /etc/custom.conf"
#docker restart "$NOMECONTAINER"
:; }

execute_main

exit 0
