#!/bin/bash

source=$(sed -n '1p' /srv/scripts/config/backupcont)

destiny=$(sed -n '2p' /srv/scripts/config/backupcont)

cd "$source"
datetime=$(date +"%d_%m_%y")

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Run this script as Root!"
    exit
    }
}

function checkB {
  # Delete files older than 3 days; Do not forget about the SLASH!
  find "$destiny"/ -type f -mtime +1 -delete
}

function dockerctrl {
  docker "$1" $(docker ps -a -q)
}

function backup {
  for dir in $(find * -maxdepth 0 ! -path "*oraclexe21c*")
    do
      tar -I 'lz4 -1 -c -' -cpf "$destiny"/"$dir"-"$datetime".tar.lz4 "$dir"
    done
}

checkA
rm /srv/containers/pihole*/log/pihole.log
dockerctrl stop &&
checkB
backup
dockerctrl start &&

exit 0
