#!/bin/bash

datetime=$(date +"%d_%m_%y_%H:%M")
source=$(sed -n '1p' /srv/containers/scripts/config/backupcont)
destiny=$(sed -n '2p' /srv/containers/scripts/config/backupcont)
cd "$source"

function start {
  files=()

while IFS= read -r -d $'\0' file; do
  files+=("$file" "")
done < <(find "$destiny" -type f -name "*.tar" -print0)

# Verificar se há pelo menos 1 arquivo ou gerar erro.
  [ ${#files[@]} -eq 0 ] && {
    clear
    echo "Nenhum arquivo encontrado em $directory"
  } || {
    file=$(dialog --stdout --title "Escolha um arquivo de Backup:" --cancel-label "Sair" --menu "Lista de backups encontrados:" 0 0 0 "${files[@]}")
    [ $? -ne 0 ] && return # Se pressionar Voltar nesta tela, ele sai do programa!
    NAME="$(basename "$file" .tar)"
    file=$(echo "$NAME" | sed 's/.\{9\}$//')

    clear ; echo "Parando o container $file"
    docker stop $file &&

    clear; echo "Fazendo backup do atual container $file"
    mkdir -p /srv/backup4restore/
    sudo tar -cvf /srv/backup4restore/"$file"-"$datetime".tar "$file" &&

    POR FAVOR CONFIRME QUE VOCE ESTA DE ACORDO COM OS RISCOS INERENTES A ESTA RESTAURACAO!
    "eu estou ciente dos riscos"

    clear; echo "Restaurando Backup! Aguarde..."
    sudo tar -xvf $file.tar -C /srv/containers/ &&

    clear; echo "Restauracao concluida! Reiniciando o container $file..."
    docker start $file &&
    sleep 3
  }
}

start

exit 1
