#!/bin/bash

hash1="cded81e2523899b1f981bab084bcf1c4"
hash2="e7ad599887b1baf90b830435dac14ba3"
hash3="4a45c115f438d5da4b6ea856153bc9d9"
hash4="445b6c94326839fcb988a096760f0e13"
hash5="f9c88e3c538ce7379fdd4bcc2c71f103"

clear; echo ""; read -p "Digite seu Token: " -r "token0"

function init {
  [ -z "$token0" ] && {
    dialog --title "ERROR" --msgbox "É necessário digitar seu Token para continuar!" 6 40
    return
  } || {
    [ "$token0" = "$hash1" ] && {
      hash01
    } || {
      [ "$token0" = "$hash2" ] && {
        hash02
      } || {
        [ "$token0" = "$hash3" ] && {
          hash03
        } || {
          [ "$token0" = "$hash4" ] && {
            hash04
          } || {
            [ "$token0" = "$hash5" ] && {
              hash05
            } || {
              error0; return
            }
          }
        }
      }
    }
  }
}

function error0 {
  clear
  dialog --title "ERROR" --msgbox "Token incorreto. \nTente novamente!" 6 30
  timeout=$((timeout+1)); sleep $timeout
  return
}

function hash01 {
  clear
  echo ""
  echo "Em Breve! bbr"
}

function hash02 {
  clear
  echo ""
  echo "Em Breve! d"
}

function hash03 {
  clear
  echo ""
  echo "Em Breve! bw"
}

function hash04 {
  clear
  echo ""
  echo "Em Breve! n"
}

function hash05 {
  clear
  echo ""
  echo "Em Breve! s"
}

init

exit 1
