#!/bin/bash

UUIDD=$(sed -n '1p' /srv/containers/scripts/config/backup_disk)
mountpoint=$(sed -n '2p' /srv/containers/scripts/config/backup_disk)

function checkA {
  [ "$EUID" -ne 0 ] && {
    echo "Run this script as Root! Exiting..."
    exit
    }
}

function checkB {
disk=$(/bin/mount -U $UUIDD $mountpoint && echo "mounted" || echo "error")
  [ "$disk" = "mounted" ]; then
    dockerctrl stop &&
    checkC
    backup
    dockerctrl start &&
  } || {
    echo "Something happened, exiting..."
    exit
  }
}

function backup {
  rsnapshot $1
}

checkA
checkB
