#!/bin/bash

# To run 23:00 everyday!
# 00 23 * * * bash /path/to/autolog

pathto="/srv/containers/dominio/log/"
logname="syslog"

scale="50000000"

datetime=$(date +"%H_%M_%S_-_%d_%m_%y")

function check_root {
  [ "$EUID" -ne 0 ] && {
    echo "Run this script as Root! Exiting..."
    exit
    }
}

function check_size {
  size=$(du --apparent-size --block-size=1 $pathto$logname | awk {print'$1'})
  [ "$size" -ge "$scale" ] && {
    sudo mv "$pathto$logname" "$pathto$logname-$datetime.bkp"
    sudo touch "$pathto$logname"
    sudo chmod 777 -R "$pathto$logname"
  } || {
    echo "Small log file. Exiting" > /dev/null
  }
}

# Start Here!
check_root
check_size

exit 1
