#!/bin/bash

# Change here to the SAME configurations of Domain to be migrated!
HOSTNAME="atomic-pi"
NAME="dominio"
NETWORKLAN="host"
USERNAME="administrador"

docker run -t -i \
-h $HOSTNAME \
--name $NAME \
--privileged \
--restart=unless-stopped \
-v /etc/localtime:/etc/localtime:ro \
--network $NETWORKLAN \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/cache/:/var/cache/samba \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/lib/:/var/lib/samba \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/log/:/var/log/samba \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/etc/:/etc/samba \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/run/:/run/samba \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/config/hosts:/etc/hosts \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/config/krb5.conf:/etc/ \
-v /home/"$USERNAME"/ACTIVE_DIRECTORY/config/resolv.conf:/etc/ \
urbancompasspony/migrate-domain:latest

#-v /mnt:/mnt \
#-v $(pwd)/FOLDER:/mnt \
